<%@ taglib prefix="a" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<fmt:setBundle basename="messages/messages"/>
<fmt:message key="common.rules.title" var="title"/>

<a:genericpage title="${title}" jsitems="${jsitems}" cssitems="${cssitem}">
    <jsp:attribute name="header"><a:nav/></jsp:attribute>
    <jsp:attribute name="menu">
        <h1><fmt:message key="common.rules.title"/></h1>
    </jsp:attribute>
    <jsp:body>
        <a:breadcrumbs items="${breadcrumbItems}"/>
        <a:alert/>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec risus massa, tincidunt eu nulla quis, dictum efficitur orci. Donec pulvinar, orci quis vehicula fringilla, nisl mi dictum lorem, et vestibulum dui libero id tellus. Nam condimentum scelerisque justo. Etiam blandit, felis at auctor ullamcorper, dui turpis aliquam velit, commodo fringilla metus libero ac nulla. Donec id metus ut mauris sodales faucibus. Sed eu elit elementum, sagittis turpis non, sagittis mauris. Vestibulum lobortis dui magna, at venenatis tellus lobortis eget. Vivamus non euismod nunc. Integer tellus nisi, iaculis a laoreet et, bibendum eget mi. Suspendisse a sollicitudin lacus, nec molestie felis. Sed sit amet suscipit purus. Vivamus ut mi nisl. Donec volutpat est quis magna imperdiet maximus.</p>
        <p>Maecenas vehicula feugiat metus in pellentesque. Phasellus ac arcu et odio maximus auctor. Nullam ac libero ut augue faucibus suscipit. Mauris condimentum lobortis erat. Vestibulum sed commodo sapien. Phasellus posuere felis sed odio feugiat, nec laoreet velit commodo. Donec venenatis nisl in mollis posuere. Donec ac tristique dolor. Aliquam blandit urna id ex feugiat, sit amet interdum lacus fermentum. Morbi sed augue leo.</p>
        <p>Etiam dignissim, augue maximus tincidunt fringilla, libero tellus rhoncus tortor, sit amet varius lacus magna efficitur justo. Pellentesque et rhoncus justo. Cras pulvinar velit eu vulputate molestie. Vivamus interdum tellus vel lacus suscipit lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce ante sem, dignissim vel ornare non, convallis ac lorem. Donec malesuada mi tellus, in aliquet lectus viverra ac. Vestibulum vitae leo gravida, porta purus vel, fermentum turpis. In eget malesuada ligula, sed consectetur elit. Cras sit amet vehicula ipsum. Proin lacinia justo in ex dictum, ac bibendum metus molestie. Aliquam et dictum purus.</p>
        <p>Ut mollis interdum tellus, quis varius quam. In nec sem sed urna condimentum laoreet. Duis ullamcorper eros a augue convallis hendrerit. Aliquam cursus suscipit lacus, suscipit aliquet mi tempor sit amet. Praesent faucibus, nibh a molestie accumsan, est odio efficitur ante, ac dapibus ante mauris vel justo. Integer leo nulla, accumsan non magna non, feugiat pretium nunc. Quisque eu nulla nisl. Vestibulum blandit hendrerit pharetra. Donec non porttitor justo. Duis a malesuada risus. Nunc lobortis diam eu pharetra tincidunt. Phasellus ultricies arcu nulla, nec molestie enim suscipit ut. Aenean et dolor venenatis, imperdiet ligula quis, euismod ante. Nulla dignissim viverra pretium. Aliquam convallis turpis at lectus aliquet commodo. Quisque tellus lorem, auctor ut consequat ut, sollicitudin eu ligula.</p>
        <p>Integer suscipit eu nisl ut mollis. Quisque convallis scelerisque ipsum nec vestibulum. Nulla lacinia consequat volutpat. Aenean posuere, purus eu luctus eleifend, mi purus mollis purus, a tempor lacus nibh eu ex. Suspendisse tortor nibh, lacinia eget elit sed, mattis condimentum leo. Sed vitae lacinia nunc. Vestibulum tincidunt, felis quis euismod interdum, sapien nunc convallis lectus, in ultricies lectus odio at felis. Mauris vel augue varius mi vehicula ornare. Duis iaculis porttitor justo ac tempor. Pellentesque ullamcorper massa id lorem rutrum, sed porttitor lacus tempus. Cras orci enim, vestibulum in nisl vitae, rutrum fermentum lectus.</p>
        <p>Nam quis blandit elit. Suspendisse commodo justo nec lacinia sagittis. Sed fermentum neque ac scelerisque rutrum. Quisque molestie justo id eros convallis molestie. Vivamus faucibus risus vitae sapien posuere, non porttitor risus venenatis. Donec vehicula enim nibh, id euismod massa porta ac. Suspendisse tristique hendrerit pharetra. Donec quis interdum mi. Nunc dictum cursus ligula commodo facilisis. Nulla faucibus ipsum vestibulum lectus ullamcorper blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <p>Cras hendrerit aliquam posuere. Curabitur a commodo risus. Vestibulum velit sem, dignissim a posuere cursus, gravida quis justo. Vestibulum lacus ligula, varius in lobortis nec, viverra sed lacus. Fusce vestibulum sit amet nisl ut pharetra. Donec at eros eu eros mollis iaculis ut quis ante. Quisque pulvinar quam nunc, a ullamcorper erat tempor sed. Proin ornare neque turpis, quis hendrerit libero rutrum sed. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla vestibulum, ipsum vel consectetur iaculis, nulla erat pretium justo, a maximus justo neque at quam. Curabitur eget rutrum leo. Donec ut interdum diam. Curabitur egestas velit id erat tincidunt, a congue tortor laoreet. Suspendisse placerat in leo et aliquet. Sed faucibus, magna ut venenatis placerat, mi tellus porta nulla, ut scelerisque sapien enim et ligula. Nullam sodales tortor tortor, non cursus augue sollicitudin quis.</p>
        <p>Donec ut lorem metus. In ut magna dignissim, tristique dui accumsan, blandit ligula. Nullam nec ullamcorper neque. Nunc at dolor ac lacus scelerisque commodo. Pellentesque dapibus, eros a hendrerit convallis, est lorem tincidunt augue, et gravida nibh ex vel quam. Donec fermentum porttitor nisi et placerat. Mauris sed venenatis turpis, id suscipit enim. Ut at ex quis tortor imperdiet vestibulum eget nec nibh. Proin cursus purus placerat iaculis lobortis.</p>
    </jsp:body>
</a:genericpage>